### ISSUE TITLE
Code highlighting is not working

### ISSUE THREAD

**Issue by JasterV** [MartenBE/mkslides#46]
**Describe the bug**

I've setup my first project, but code highlight is not working

This is my `mkslides.yml`

```yml
slides:
    theme: league
    highlight_theme: vs
revealjs:
    history: true
    slideNumber: c/t
```

And the code blocks look like this:

![Image](https://github.com/user-attachments/assets/05f2f7dd-de1f-42f3-9044-57284f8d3f52)
